ienokado/debayashi-koreyashi

- src/public/css/app.css
- src/resources/sass/_top-animation.scss
- src/resources/views/top.blade.php
> top画面にアニメーション追加

- README.md
> SpotifyAPIの設定方法を追記

- src/resources/views/search/index.blade.php
- Spotifyのリンクが該当のデータがない場合にエラーになっていたため修正
なし
> Spotifyで取得情報がない場合の制御追加

- src/public/css/app.css
- src/resources/sass/_search.scss
- src/resources/views/search/index.blade.php
- コンビ名, アーティスト名, 曲名の長い時のレイアウト調整
- https://github.com/ienokado/debayashi-koreyashi/issues/11
> コンビ名, アーティスト名, 曲名の長い時のレイアウト調整

- src/public/css/app.css
- src/resources/sass/app.scss
- src/resources/views/common/head.blade.php
- src/resources/views/layouts/app.blade.php
- src/resources/views/top.blade.php
- FontAwesomeの読み込み箇所をapp.scssに統一
- issueなし
> fontawesomeの読み込み箇所を変更

- src/public/css/app.css
- src/resources/sass/_comedian.scss
- src/resources/sass/_footer.scss
- src/resources/sass/_placeholder.scss
- src/resources/sass/_search.scss
- src/resources/sass/_top.scss
- src/resources/sass/_ui-common.scss
- src/resources/sass/_variables.scss
- src/resources/sass/app.scss
- src/resources/views/common/footer.blade.php
- src/resources/views/common/head.blade.php
- src/resources/views/top.blade.php
- 実機での表示修正
- https://github.com/ienokado/debayashi-koreyashi/issues/52
- スマホでは游ゴシックが有料のため、さわらびフォントに変更
> トップ画面 スマホレイアウト修正

- src/public/css/app.css
- src/resources/sass/_search.scss
- src/resources/sass/_variables.scss
- src/resources/views/search/index.blade.php
- 検索結果画面のレスポンシブ対応
- https://github.com/ienokado/debayashi-koreyashi/issues/43
- 検索ヒット時に画面高さに応じて検索結果カードの表示位置を調整
> 検索結果画面のレスポンシブ対応

- src/app/Http/Kernel.php
- src/app/Http/Middleware/RequestLogger.php
- src/config/const.php
> 芸人検索時の入力キーワードをログに残す

- src/app/Http/Kernel.php
- src/app/Http/Middleware/RequestLogger.php
- src/config/logging.php
- src/routes/web.php
> requestログの書き出しはでばやし検索処理のときのみにする

- README.md
- src/.env.circleci
- src/.env.example
- src/app/Exceptions/Handler.php
- src/composer.json
- src/composer.lock
- src/config/logging.php
- src/config/sentry.php
- 致命的エラーはSentryで管理する
- https://github.com/ienokado/debayashi-koreyashi/issues/35
> Sentryでのエラー通知設定

- src/routes/web.php
> 本番環境でのHTTPS通信化

- src/public/css/app.css
- src/resources/sass/_search.scss
- src/resources/views/search/index.blade.php
- プレビューボタンのレイアウトを修正
- なし
- スマホ実機での表示確認未済
> プレビューボタンのレイアウト修正

- src/public/css/app.css
- src/resources/sass/_comedian.scss
> TOPレイアウトの調整

- src/resources/views/common/head.blade.php
- GoogleAnalyticsで計測する準備を整える
- https://github.com/ienokado/debayashi-koreyashi/issues/68
> GoogleAnalyticsのタグを追加

- src/resources/views/common/head.blade.php
- GoogleAdsenseで広告表示の準備
- https://github.com/ienokado/debayashi-koreyashi/issues/67
- そもそもコンテンツ数が少ないと広告表示の認証がおりないので、ダメかもしれない
- その場合はコンテンツを増やすしかない。
- 一旦Webリリースした後にスマホアプリiOSとかで作ってみてまた挑戦するのも手段の一つ
> GoogleAdsenseタグを追加

- src/public/css/app.css
- src/resources/sass/_comedian.scss
- src/resources/sass/_variables.scss
> トップ画面のレイアウト修正(iPhone8)

- src/public/css/app.css
- src/resources/sass/_search.scss
- src/resources/views/common/head.blade.php
- src/resources/views/search/index.blade.php
- アートワーク画像のサイズ調整
　なし
縦横比が異なる画像でチェック
- 縦長な画像：さや香
- 横長な画像：ダークニンゲン
実機動作未済
> アートワーク画像のサイズ調整

- src/app/Http/Controllers/DebayashiSearchController.php
- src/app/Models/Debayashi.php
- src/app/Models/SpotifyInfo.php
- src/database/migrations/2020_02_13_164155_create_spotify_info_table.php
- src/resources/views/search/index.blade.php
- Spotify API問合せ回数を減らす対応
- https://github.com/ienokado/debayashi-koreyashi/issues/72
> Spotify検索結果をDB保存する

- src/app/Facades/AppleMusicFacade.php
- src/app/Http/Controllers/DebayashiSearchController.php
- src/app/Models/AppleMusicInfo.php
- src/app/Models/Debayashi.php
- src/database/migrations/2020_02_13_164244_create_apple_music_info_table.php
- src/resources/views/search/index.blade.php
- Apple Music APIの問合せ回数を減らす対応
- https://github.com/ienokado/debayashi-koreyashi/issues/75
> AppleMusic検索結果をDB保存する

- src/app/Http/Controllers/DebayashiSearchController.php
- src/database/csv/debayashis.csv
- src/resources/views/search/index.blade.php
- issue参照
- https://github.com/ienokado/debayashi-koreyashi/issues/78
> AppleMusic検索時"&"の文字列は"and"に変換

- .circleci/config.yml
- src/phpunit.xml
- CircleCIでのPHPUnitのCoverage設定を追加
なし
> Coverage設定追加

- README.md
- ステータスをつけて気分をあげたい
- テストがない危機意識
なし
> READMEにバッジを表示

- src/package-lock.json
- src/package.json
> acornの脆弱性回避対応（バージョンアップ）

- src/package-lock.json
- src/package.json
> package.jsonの更新

- src/resources/views/search/index.blade.php
> シェアボタン の修正対応

- src/app/Http/Controllers/DebayashiSearchController.php
- src/config/const.php
- src/resources/views/search/index.blade.php
> シェアボタンのコメント修正

- src/app/Http/Middleware/RequestLogger.php
> 芸人検索のキーワードのログ情報を変更

- src/resources/views/common/head.blade.php
> GoogleAdsenseタグを再び有効に

- README.md
> 管理ユーザーのデータ追加説明

- src/app/Http/Controllers/Controller.php
- コミット漏れ
- 管理画面がPCで見れるようにパスで制御
-
> 管理画面はPCでもみれるように

- src/app/Http/Controllers/Controller.php
> 管理画面のTOPページがPCで見れない

- src/app/Http/Controllers/Admin/DebayashiController.php
- src/app/Http/Controllers/Admin/LogController.php
- src/app/Http/Controllers/Admin/TopController.php
- src/resources/views/admin/debayashi/edit.blade.php
- src/resources/views/admin/debayashi/index.blade.php
- src/resources/views/admin/layout/layout.blade.php
- src/resources/views/admin/layout/topBar.blade.php
- src/resources/views/admin/top.blade.php
- src/routes/admin.php
> 出囃子一覧と出囃子登録機能

- src/app/Http/Controllers/Admin/ComedianGroupController.php
- src/app/Http/Middleware/GenerateMenus.php
- src/resources/views/admin/comedian_group/edit.blade.php
- src/resources/views/admin/comedian_group/index.blade.php
- src/routes/admin.php
- 芸人一覧/登録機能を追加することでブラウザから登録できるように
データが多いと表示が遅くなるのは別途対応
> 芸人一覧と芸人登録機能

- src/public/robots.txt
> robots.txtを更新（Adsenseを許可できるよう）

- src/resources/views/search/index.blade.php
- プレビューボタンを押下してもプレビューが再生されないバグを修正
- なし
> プレビューURLが取得出来る場合のみプレビューボタン生成

- src/package-lock.json
- src/package.json
- npm updateによるライブラリのバージョンアップデート
なし
> npm update

- src/public/css/app.css
- src/resources/sass/_comedian.scss
- src/resources/sass/_logo.scss
- src/resources/sass/_top-animation.scss
- src/resources/sass/_top.scss
- src/resources/sass/_variables.scss
- src/resources/views/top.blade.php
- トップ画面のPC用のデザインを実装
- なし
- その他一部修正
> トップ画面のPC用デザイン実装

- src/app/Facades/AppleMusicFacade.php
- src/app/Http/Controllers/Debayashi/HistoryController.php
- src/app/Models/ComedianGroup.php
- src/app/Services/AppleMusicService.php
- src/app/Services/SpotifyService.php
- src/config/services.php
- src/resources/views/debayashi/history.blade.php
- src/resources/views/debayashi/ranking.blade.php
- src/routes/web.php
- 検索履歴を絞り込みできるように
- 気になるところも合わせて修正
- https://github.com/ienokado/debayashi-koreyashi/issues/128
- ページングは別PRで対応予定
- 本当は非同期通信にしたいところ
> 検索履歴の絞り込み処理を追加

- src/app/Exceptions/Handler.php
- src/app/Exceptions/OnlyMobileException.php
- src/app/Http/Controllers/Controller.php
- src/resources/views/debayashi/history.blade.php
- src/resources/views/debayashi/list-item.blade.php
- src/resources/views/debayashi/search.blade.php
- src/resources/views/errors/only_mobile.blade.php
- src/resources/views/top.blade.php
- PCレイアウトの調整ができたのでPCアクセスエラーを削除する
なし
> PCアクセスエラーを削除

- src/composer.json
- src/composer.lock
https://sentry.io/organizations/ienokado/issues/1700693291/
管理画面ログイン時のエラーが発生したので修正
なし
> jwt-authのライブラリを更新

- src/composer.json
- src/composer.lock
> [2020-05-31]リリース

- src/resources/views/top.blade.php
- トップページのフッターの検索ボタンを選択中にしておく
なし
> トップページのフッター修正

- src/public/css/admin.css
- src/resources/sass/admin/vendor/themify-icons.css
> 管理画面のアイコンのファイルパス修正

- src/app/Http/Controllers/Controller.php
- src/app/Http/Controllers/Debayashi/RankingController.php
- src/app/Models/SearchHistory.php
- src/config/const.php
- src/public/css/app.css
- src/public/js/admin.js
- src/public/js/app.js
- src/resources/sass/_history.scss
- src/resources/sass/_paging-btn.scss
- src/resources/sass/_ranking.scss
- src/resources/sass/app.scss
- src/resources/views/common/head.blade.php
- src/resources/views/debayashi/history.blade.php
- src/resources/views/debayashi/ranking.blade.php
- ランキング画面をページングする
- https://github.com/ienokado/debayashi-koreyashi/issues/139
- Controllerでのページネーション用データ生成
− ページング用ボタンを共通化(css)
> ランキング画面をページングする

- src/public/js/app.js
- src/resources/js/playDebayashis.js
- src/resources/views/debayashi/list-item.blade.php
- src/resources/views/debayashi/search.blade.php
- 描画時に変な場所に再生ボタンが表示されているのを修正する
- なし
> 再生ボタンのベースクラス付与方法修正

- src/public/css/app.css
- src/resources/sass/_card-list-item.scss
- src/resources/views/debayashi/list-item.blade.php
- アートワークがない場合のスタイルを実装
- https://github.com/ienokado/debayashi-koreyashi/issues/131
> 検索履歴/ランキング画面のアルバム画像ない場合のデザイン
